apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: baribhara
  labels:
    app: admin-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
        tier: backend
    spec:
      containers:
      - name: admin-service
        image: baribhara/admin-service:latest
        ports:
        - containerPort: 3008
        - containerPort: 50058
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3008"
        - name: GRPC_PORT
          value: "50058"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: baribhara-secrets
              key: DATABASE_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: REDIS_PORT
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: KAFKA_BROKERS
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3008
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3008
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: baribhara
  labels:
    app: admin-service
spec:
  selector:
    app: admin-service
  ports:
  - name: http
    port: 3008
    targetPort: 3008
    protocol: TCP
  - name: grpc
    port: 50058
    targetPort: 50058
    protocol: TCP
  type: ClusterIP
