apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: baribhara
  labels:
    app: notification-service
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        tier: backend
    spec:
      containers:
      - name: notification-service
        image: baribhara/notification-service:latest
        ports:
        - containerPort: 3006
        - containerPort: 50056
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3006"
        - name: GRPC_PORT
          value: "50056"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: baribhara-secrets
              key: DATABASE_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: REDIS_PORT
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: KAFKA_BROKERS
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: SMTP_HOST
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: SMTP_USER
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: baribhara-secrets
              key: SMTP_PASSWORD
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: TWILIO_ACCOUNT_SID
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: baribhara-secrets
              key: TWILIO_AUTH_TOKEN
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            configMapKeyRef:
              name: baribhara-config
              key: TWILIO_PHONE_NUMBER
        - name: WHATSAPP_TOKEN
          valueFrom:
            secretKeyRef:
              name: baribhara-secrets
              key: WHATSAPP_TOKEN
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3006
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3006
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: baribhara
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - name: http
    port: 3006
    targetPort: 3006
    protocol: TCP
  - name: grpc
    port: 50056
    targetPort: 50056
    protocol: TCP
  type: ClusterIP
