global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'property-service'
    static_configs:
      - targets: ['property-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'tenant-service'
    static_configs:
      - targets: ['tenant-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'invoice-service'
    static_configs:
      - targets: ['invoice-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3006']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'report-service'
    static_configs:
      - targets: ['report-service:3007']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:3008']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
